### PR TITLE
[docdb] fix issue-4262

### LINKED ISSUE #4262: num_tablet_servers_live metric does not reset when a master's status changes from leader to follower
Impact appears to be simply cosmetic...this can be reproduced by triggering a master leader that does not involve restarting the active leader's yb-master process. Observed in v2.1.3.0.

### PR DESCRIPTION
**Pull request by SGZW**
fix #4262

### CODE REVIEW

**Comment by SGZW** [comment]
@rahuldesirazu please review this when you are free, thanks

**Comment by rahuldesirazu** [comment]
@SGZW Code looks good! I'll go ahead and run it through our test suite.

File: src/yb/master/catalog_manager_bg_tasks.cc [hunk 1]
```diff
@@ -175,6 +175,9 @@ void CatalogManagerBgTasks::Run() {
 
       // Start the tablespace background task.
       catalog_manager_->StartTablespaceBgTaskIfStopped();
+    } else {
```
Comment (rahuldesirazu) [inline src/yb/master/catalog_manager_bg_tasks.cc:178]: I think there should be a `if (!l.catalog_status().ok())` clause above this, I think its best to put this there.

**Review by rahuldesirazu — CHANGES_REQUESTED** [review]

**Comment by rahuldesirazu** [comment]
@SGZW Actually sorry just had one small comment, will put it through the test suite once its addressed.

File: src/yb/master/catalog_manager_bg_tasks.cc (hunk 1 above)
Comment (SGZW) [reply src/yb/master/catalog_manager_bg_tasks.cc:178]: when (!l.catalog_status().ok()) is true,  catalog-manager status is either kConstructed or kStarting, it means catalog manager is init that metrics already reset, we should do nothing. we only need to clear metrics when raft role change from leader to other state so that reset metrics in branch "else"

**Comment by SGZW** [comment]
> @SGZW Actually sorry just had one small comment, will put it through the test suite once its addressed.

**Comment by SGZW** [comment]
> @SGZW Actually sorry just had one small comment, will put it through the test suite once its addressed.

please recheck my comment, thanks

File: src/yb/master/catalog_manager_bg_tasks.cc (hunk 1 above)
Comment (rahuldesirazu) [reply src/yb/master/catalog_manager_bg_tasks.cc:178]: Sorry for the late reply, that's a fair point. The code looks good and I will put it through our jenkins pipeline.

Comment (SGZW) [reply src/yb/master/catalog_manager_bg_tasks.cc:178]: thanks
